import React, { useMemo, useState } from 'react';
import CounterPOS from './CounterPOS.jsx';
import { loadCloudLocations, loadLocations, makeLocationId, saveCloudLocations, saveLocations } from './locationStore.js';
import { supabase } from './supabaseClient.js';
import { listManagerOrders, updateOrderStatus } from './orderStore.js';
import AnalyticsDashboard from './AnalyticsDashboard.jsx';
import KitchenDisplay from './KitchenDisplay.jsx';
import TeamManager from './TeamManager.jsx';

const serviceOptions = ['dine-in', 'pickup', 'delivery', 'catering', 'private-events', 'lunch'];
const menusByRole = { owner: ['Overview', 'Analytics', 'Counter / POS', 'Kitchen display', 'Locations', 'Menu & availability', 'Orders', 'Offers & rewards', 'Team settings'], manager: ['Overview', 'Analytics', 'Counter / POS', 'Kitchen display', 'Locations', 'Menu & availability', 'Orders', 'Offers & rewards'], cashier: ['Counter / POS'], kitchen: ['Kitchen display'] };
const demoOrders = [{ id: 'ORD-1042', guest: 'Sarah M.', location: 'Clifton', type: 'Pickup', total: '$42.97', status: 'New' }, { id: 'ORD-1041', guest: 'Daniel R.', location: 'Clifton', type: 'Delivery', total: '$67.85', status: 'Preparing' }];
const blankLocation = { name: '', address: '', phone: '', services: ['dine-in', 'pickup'], hours: { sunday: '', weekday: '', saturday: '' }, rewardOffer: '', menuNote: '' };

export default function AdminDashboard() {
  const [locations, setLocations] = useState(() => loadLocations());
  const [activeLocation, setActiveLocation] = useState(() => loadLocations()[0].id);
  const [section, setSection] = useState('Overview');
  const [notice, setNotice] = useState('Manage locations, orders, offers, and daily operations from one place.');
  const [orders, setOrders] = useState(demoOrders);
  const [adding, setAdding] = useState(false);
  const [session, setSession] = useState(null);
  const [authReady, setAuthReady] = useState(false);
  const [accessReady, setAccessReady] = useState(false);
  const [managerRole, setManagerRole] = useState(null);
  const current = useMemo(() => locations.find((location) => location.id === activeLocation) || locations[0], [activeLocation, locations]);
  const persist = async (next, message) => { if (!managerRole) return setNotice('Owner access is required before changes can be saved.'); const { error } = await saveCloudLocations(next); if (error) return setNotice('We could not save this change yet. Check Owner access and try again.'); setLocations(next); saveLocations(next); setNotice(`${message} Saved successfully.`); };
  const updateCurrent = (patch) => persist(locations.map((location) => location.id === current.id ? { ...location, ...patch } : location), `${current.name} updated. Refresh the customer tab to see the location-specific details.`);
  const addLocation = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = form.get('name').trim(); if (!name) return; const newLocation = { ...blankLocation, id: makeLocationId(name), name, address: form.get('address').trim() || 'Address to be configured', phone: form.get('phone').trim(), services: ['dine-in', 'pickup'], rewardOffer: form.get('rewardOffer').trim() || 'Join rewards to earn points and receive member offers.', menuNote: form.get('menuNote').trim() || `Menu for ${name}.` }; persist([...locations, newLocation], `${name} was added. Complete its details, then save.`); setActiveLocation(newLocation.id); setAdding(false); };
  const menu = menusByRole[managerRole] || [];
  React.useEffect(() => { if (!supabase) { setAuthReady(true); return; } supabase.auth.getSession().then(({ data }) => { setSession(data.session); setAuthReady(true); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => listener.subscription.unsubscribe(); }, []);
  React.useEffect(() => { if (!session || !supabase) { setAccessReady(true); return; } setAccessReady(false); supabase.from('staff_profiles').select('role').eq('user_id', session.user.id).maybeSingle().then(({ data }) => { setManagerRole(data?.role || null); setAccessReady(true); }); }, [session]);
  React.useEffect(() => { const allowed = menusByRole[managerRole]; if (allowed?.length && !allowed.includes(section)) setSection(allowed[0]); }, [managerRole]);
  React.useEffect(() => { if (!session) return; listManagerOrders().then(({ orders: liveOrders, error }) => { if (liveOrders.length) setOrders(liveOrders); if (error) setNotice('The order queue is temporarily unavailable.'); }); }, [session, section]);
  React.useEffect(() => { loadCloudLocations().then(({ locations: cloud }) => { if (cloud) { setLocations(cloud); setActiveLocation(cloud[0].id); setNotice('Location details are ready.'); } }); }, []);
  if (!authReady) return <div className="admin-auth-shell">Checking secure staff access…</div>;
  if (!session) return <AdminLogin />;
  if (!accessReady) return <div className="admin-auth-shell">Checking owner access…</div>;
  if (!managerRole) return <OwnerAccess email={session.user.email} onSignOut={() => supabase.auth.signOut()} />;
  return <div className="admin-shell"><aside className="admin-sidebar"><a className="brand" href="/">AMBAR <span>DIRECT</span><small>MANAGER PORTAL</small></a><p className="admin-label">SIGNED IN</p><p className="admin-user">{session.user.email}</p><p className="admin-role">{managerRole}</p><button className="admin-signout" onClick={() => supabase.auth.signOut()}>Sign out</button><p className="admin-label">RESTAURANT GROUP</p><select value={activeLocation} onChange={(event) => setActiveLocation(event.target.value)}>{locations.map((location) => <option key={location.id} value={location.id}>{location.name.replace('Ambar India ', '')}</option>)}</select><nav className="admin-nav">{menu.map((item) => <button key={item} className={section === item ? 'active' : ''} onClick={() => setSection(item)}>{item}</button>)}</nav><a className="admin-back" href="/">← View customer website</a></aside><main className="admin-main"><header className="admin-header"><div><p className="eyebrow">Manager portal</p><h1>{section}</h1></div>{section === 'Locations' && <button className="admin-save" onClick={() => setAdding(true)}>Add a location</button>}</header>{section === 'Overview' && <Overview orders={orders} locations={locations} />}{section === 'Analytics' && <AnalyticsDashboard orders={orders} locations={locations} />}{section === 'Counter / POS' && <CounterPOS locationId={current.id} />}{section === 'Kitchen display' && <KitchenDisplay initialOrders={orders} />}{section === 'Locations' && <LocationSettings location={current} onSave={updateCurrent} />}{section === 'Menu & availability' && <MenuManager location={current} onSave={updateCurrent} />}{section === 'Orders' && <OrderManager orders={orders} setOrders={setOrders} />}{section === 'Offers & rewards' && <Rewards location={current} onSave={updateCurrent} />}{section === 'Team settings' && <TeamManager locations={locations} currentRole={managerRole} />}{adding && <AddLocation onClose={() => setAdding(false)} onSubmit={addLocation} />}</main></div>;
}
function AdminLogin() { const [email, setEmail] = useState('Amberindia@test.com'); const [password, setPassword] = useState(''); const [message, setMessage] = useState('Sign in with your owner account, or request a secure email link.'); const submit = async (event) => { event.preventDefault(); if (!supabase) return setMessage('Secure sign-in is not available right now.'); const { error } = await supabase.auth.signInWithPassword({ email, password }); setMessage(error ? 'We could not sign you in. Check your email and password.' : 'Signed in.'); }; const sendLink = async () => { if (!supabase) return setMessage('Secure sign-in is not available right now.'); const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/admin` } }); setMessage(error ? 'We could not send the sign-in email. Please try again.' : `A secure sign-in link was sent to ${email}. Open it on this device.`); }; return <main className="admin-auth-shell"><form className="admin-auth-card" onSubmit={submit}><a className="brand" href="/">AMBAR <span>DIRECT</span><small>MANAGER PORTAL</small></a><p className="eyebrow">Secure staff access</p><h1>Sign in to manage your restaurants.</h1><p>{message}</p><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><button className="primary-button" type="submit">Sign in →</button><button className="auth-link-button" type="button" onClick={sendLink}>Email me a secure sign-in link</button></form></main>; }
function Overview({ orders, locations }) { return <><section className="stat-grid"><Stat title="Today's sales" value="$1,248.60" note="12% vs last Tuesday" /><Stat title="Orders today" value="43" note="7 currently active" /><Stat title="Rewards members" value="1,284" note="24 this month" /><Stat title="Locations active" value={locations.length} note="Configured locations" /></section><section className="admin-card"><div className="card-heading"><div><h2>Live orders</h2><p>Keep every guest moving through service.</p></div></div><OrderTable orders={orders} /></section></>; }
function Stat({ title, value, note }) { return <article className="stat"><p>{title}</p><strong>{value}</strong><small>{note}</small></article>; }
function LocationSettings({ location, onSave }) { const [draft, setDraft] = useState(location); const change = (field, value) => setDraft({ ...draft, [field]: value }); const toggle = (service) => change('services', draft.services.includes(service) ? draft.services.filter((item) => item !== service) : [...draft.services, service]); return <section className="admin-card"><div className="card-heading"><div><h2>{location.name}</h2><p>Everything on this screen belongs only to this location.</p></div><span className="status-dot">Open</span></div><div className="form-grid"><label>Location name<input value={draft.name} onChange={(event) => change('name', event.target.value)} /></label><label>Phone number<input value={draft.phone || ''} onChange={(event) => change('phone', event.target.value)} placeholder="Add phone number" /></label><label className="wide">Street address<input value={draft.address} onChange={(event) => change('address', event.target.value)} /></label><label>Sunday hours<input value={draft.hours?.sunday || ''} onChange={(event) => change('hours', { ...draft.hours, sunday: event.target.value })} placeholder="Closed or 10:30 AM – 9:30 PM" /></label><label>Weekday hours<input value={draft.hours?.weekday || ''} onChange={(event) => change('hours', { ...draft.hours, weekday: event.target.value })} placeholder="10:30 AM – 10:00 PM" /></label></div><h3>Services available at this location</h3><div className="service-toggles">{serviceOptions.map((service) => <label key={service}><input type="checkbox" checked={draft.services.includes(service)} onChange={() => toggle(service)} /><span>{service.replace('-', ' ')}</span></label>)}</div><button className="admin-save settings-save" onClick={() => onSave(draft)}>Save location details</button></section>; }
function MenuManager({ location, onSave }) { const [note, setNote] = useState(location.menuNote || ''); return <section className="admin-card"><div className="card-heading"><div><h2>{location.name} menu</h2><p>This location can display its own menu message and availability.</p></div></div><label className="full-field">Menu message shown to customers<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><div className="menu-table">{[['Chicken Tikka Masala', '$22.99'], ['Saag Paneer', '$22.99'], ['Garlic Naan', '$7.99'], ['Vegetable Samosa', '$9.89']].map(([name, price]) => <div key={name}><b>{name}</b><span>{price}</span><label className="available"><input type="checkbox" defaultChecked />Available</label><button>Edit</button></div>)}</div><button className="admin-save settings-save" onClick={() => onSave({ menuNote: note })}>Save menu message</button></section>; }
function Rewards({ location, onSave }) { const [offer, setOffer] = useState(location.rewardOffer || ''); return <section className="admin-card"><div className="card-heading"><div><h2>{location.name} rewards</h2><p>This offer appears in the selected location's customer page.</p></div></div><label className="full-field">Location reward offer<textarea value={offer} onChange={(event) => setOffer(event.target.value)} /></label><button className="admin-save settings-save" onClick={() => onSave({ rewardOffer: offer })}>Save reward offer</button></section>; }
function OrderManager({ orders, setOrders }) { const change = async (id, status) => { const { error } = await updateOrderStatus(id, status); if (!error) setOrders(orders.map((order) => order.id === id ? { ...order, status } : order)); }; const stages = [['new','New orders'],['preparing','Being prepared'],['ready','Ready for pickup'],['completed','Completed']]; return <><section className="kitchen-board">{stages.map(([status,title]) => <article key={status}><h3>{title}<span>{orders.filter((order) => order.status === status).length}</span></h3>{orders.filter((order) => order.status === status).slice(0, 8).map((order) => <div className="kitchen-ticket" key={order.id}><b>{order.order_reference || order.id}</b><small>{order.guest_name || order.guest || 'Walk-in'} · {(order.order_type || order.type || '').replace('-', ' ')}</small><p>{order.order_items?.map((item) => `${item.quantity}× ${item.name}`).join(', ') || 'Items awaiting detail'}</p><select value={order.status} onChange={(event) => change(order.id, event.target.value)}><option value="new">New</option><option value="preparing">Being prepared</option><option value="ready">Ready</option><option value="completed">Completed</option></select></div>)}</article>)}</section><section className="admin-card"><div className="card-heading"><div><h2>All orders</h2><p>Every direct and in-house order in one queue.</p></div></div><OrderTable orders={orders} onChange={change} /></section></>; }
function OrderTable({ orders, onChange }) { return <div className="order-table"><div className="order-head"><span>Order</span><span>Guest</span><span>Location</span><span>Type</span><span>Total</span><span>Status</span></div>{orders.map((order) => <div className="order-row" key={order.id}><b>{order.order_reference || order.id}</b><span>{order.guest_name || order.guest || 'Walk-in'}</span><span>{order.location_id || order.location}</span><span>{(order.order_type || order.type || '').replace('-', ' ')}</span><span>{typeof order.total === 'number' ? `$${order.total.toFixed(2)}` : order.total}</span>{onChange ? <select value={order.status} onChange={(event) => onChange(order.id, event.target.value)}><option value="new">New</option><option value="preparing">Cooking</option><option value="ready">Ready</option><option value="completed">Completed</option></select> : <em>{order.status}</em>}</div>)}</div>; }
function Team() { return <section className="admin-card"><h2>Team access</h2><p>Give each location only the staff permissions it needs.</p></section>; }
function OwnerAccess({ email, onSignOut }) { return <main className="admin-auth-shell"><section className="admin-auth-card"><a className="brand" href="/">AMBAR <span>DIRECT</span><small>MANAGER PORTAL</small></a><p className="eyebrow">Owner access needed</p><h1>This account cannot edit restaurant data yet.</h1><p>{email} is signed in, but it has not been added as an Owner or Manager. Run the owner-access setup once, then sign in again.</p><button className="primary-button" onClick={onSignOut}>Sign out</button></section></main>; }
function AddLocation({ onClose, onSubmit }) { return <div className="modal-backdrop"><form className="location-modal admin-add" onSubmit={onSubmit}><button type="button" className="close-button" onClick={onClose}>×</button><p className="eyebrow">Restaurant group</p><h2>Add a new location</h2><label>Location name<input name="name" placeholder="Ambar India Oakley" autoFocus /></label><label>Street address<input name="address" placeholder="123 Main Street, Cincinnati, OH" /></label><label>Phone number<input name="phone" placeholder="(513) 000-0000" /></label><label>Customer menu message<textarea name="menuNote" placeholder="Fresh menu for this location." /></label><label>Reward offer<textarea name="rewardOffer" placeholder="Free Garlic Naan with orders over $35" /></label><button className="primary-button" type="submit">Create location →</button></form></div>; }
