import React, { useMemo, useState } from 'react';
import CounterPOS from './CounterPOS.jsx';
import { loadLocations, makeLocationId, saveLocations } from './locationStore.js';

const serviceOptions = ['dine-in', 'pickup', 'delivery', 'catering', 'private-events', 'lunch'];
const demoOrders = [{ id: 'ORD-1042', guest: 'Sarah M.', location: 'Clifton', type: 'Pickup', total: '$42.97', status: 'New' }, { id: 'ORD-1041', guest: 'Daniel R.', location: 'Clifton', type: 'Delivery', total: '$67.85', status: 'Preparing' }];
const blankLocation = { name: '', address: '', phone: '', services: ['dine-in', 'pickup'], hours: { sunday: '', weekday: '', saturday: '' }, rewardOffer: '', menuNote: '' };

export default function AdminDashboard() {
  const [locations, setLocations] = useState(() => loadLocations());
  const [activeLocation, setActiveLocation] = useState(() => loadLocations()[0].id);
  const [section, setSection] = useState('Overview');
  const [notice, setNotice] = useState('Demo mode: changes save to this browser and update the customer site in another tab.');
  const [orders, setOrders] = useState(demoOrders);
  const [adding, setAdding] = useState(false);
  const current = useMemo(() => locations.find((location) => location.id === activeLocation) || locations[0], [activeLocation, locations]);
  const persist = (next, message) => { setLocations(next); saveLocations(next); setNotice(message); };
  const updateCurrent = (patch) => persist(locations.map((location) => location.id === current.id ? { ...location, ...patch } : location), `${current.name} updated. Refresh the customer tab to see the location-specific details.`);
  const addLocation = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = form.get('name').trim(); if (!name) return; const newLocation = { ...blankLocation, id: makeLocationId(name), name, address: form.get('address').trim() || 'Address to be configured', phone: form.get('phone').trim(), services: ['dine-in', 'pickup'], rewardOffer: form.get('rewardOffer').trim() || 'Join rewards to earn points and receive member offers.', menuNote: form.get('menuNote').trim() || `Menu for ${name}.` }; persist([...locations, newLocation], `${name} was added. Complete its details, then save.`); setActiveLocation(newLocation.id); setAdding(false); };
  const menu = ['Overview', 'Counter / POS', 'Locations', 'Menu & availability', 'Orders', 'Offers & rewards', 'Team settings'];
  return <div className="admin-shell"><aside className="admin-sidebar"><a className="brand" href="/">AMBAR <span>DIRECT</span><small>MANAGER PORTAL</small></a><p className="admin-label">RESTAURANT GROUP</p><select value={activeLocation} onChange={(event) => setActiveLocation(event.target.value)}>{locations.map((location) => <option key={location.id} value={location.id}>{location.name.replace('Ambar India ', '')}</option>)}</select><nav className="admin-nav">{menu.map((item) => <button key={item} className={section === item ? 'active' : ''} onClick={() => setSection(item)}>{item}</button>)}</nav><a className="admin-back" href="/">← View customer website</a></aside><main className="admin-main"><header className="admin-header"><div><p className="eyebrow">Manager portal</p><h1>{section}</h1></div>{section === 'Locations' && <button className="admin-save" onClick={() => setAdding(true)}>Add a location</button>}</header><p className="admin-notice">{notice}</p>{section === 'Overview' && <Overview orders={orders} locations={locations} />}{section === 'Counter / POS' && <CounterPOS />}{section === 'Locations' && <LocationSettings location={current} onSave={updateCurrent} />}{section === 'Menu & availability' && <MenuManager location={current} onSave={updateCurrent} />}{section === 'Orders' && <OrderManager orders={orders} setOrders={setOrders} />}{section === 'Offers & rewards' && <Rewards location={current} onSave={updateCurrent} />}{section === 'Team settings' && <Team />}{adding && <AddLocation onClose={() => setAdding(false)} onSubmit={addLocation} />}</main></div>;
}
function Overview({ orders, locations }) { return <><section className="stat-grid"><Stat title="Today's sales" value="$1,248.60" note="12% vs last Tuesday" /><Stat title="Orders today" value="43" note="7 currently active" /><Stat title="Rewards members" value="1,284" note="24 this month" /><Stat title="Locations active" value={locations.length} note="Configured locations" /></section><section className="admin-card"><div className="card-heading"><div><h2>Live orders</h2><p>Keep every guest moving through service.</p></div></div><OrderTable orders={orders} /></section></>; }
function Stat({ title, value, note }) { return <article className="stat"><p>{title}</p><strong>{value}</strong><small>{note}</small></article>; }
function LocationSettings({ location, onSave }) { const [draft, setDraft] = useState(location); const change = (field, value) => setDraft({ ...draft, [field]: value }); const toggle = (service) => change('services', draft.services.includes(service) ? draft.services.filter((item) => item !== service) : [...draft.services, service]); return <section className="admin-card"><div className="card-heading"><div><h2>{location.name}</h2><p>Everything on this screen belongs only to this location.</p></div><span className="status-dot">Open</span></div><div className="form-grid"><label>Location name<input value={draft.name} onChange={(event) => change('name', event.target.value)} /></label><label>Phone number<input value={draft.phone || ''} onChange={(event) => change('phone', event.target.value)} placeholder="Add phone number" /></label><label className="wide">Street address<input value={draft.address} onChange={(event) => change('address', event.target.value)} /></label><label>Sunday hours<input value={draft.hours?.sunday || ''} onChange={(event) => change('hours', { ...draft.hours, sunday: event.target.value })} placeholder="Closed or 10:30 AM – 9:30 PM" /></label><label>Weekday hours<input value={draft.hours?.weekday || ''} onChange={(event) => change('hours', { ...draft.hours, weekday: event.target.value })} placeholder="10:30 AM – 10:00 PM" /></label></div><h3>Services available at this location</h3><div className="service-toggles">{serviceOptions.map((service) => <label key={service}><input type="checkbox" checked={draft.services.includes(service)} onChange={() => toggle(service)} /><span>{service.replace('-', ' ')}</span></label>)}</div><button className="admin-save settings-save" onClick={() => onSave(draft)}>Save location details</button></section>; }
function MenuManager({ location, onSave }) { const [note, setNote] = useState(location.menuNote || ''); return <section className="admin-card"><div className="card-heading"><div><h2>{location.name} menu</h2><p>This location can display its own menu message and availability.</p></div></div><label className="full-field">Menu message shown to customers<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><div className="menu-table">{[['Chicken Tikka Masala', '$22.99'], ['Saag Paneer', '$22.99'], ['Garlic Naan', '$7.99'], ['Vegetable Samosa', '$9.89']].map(([name, price]) => <div key={name}><b>{name}</b><span>{price}</span><label className="available"><input type="checkbox" defaultChecked />Available</label><button>Edit</button></div>)}</div><button className="admin-save settings-save" onClick={() => onSave({ menuNote: note })}>Save menu message</button></section>; }
function Rewards({ location, onSave }) { const [offer, setOffer] = useState(location.rewardOffer || ''); return <section className="admin-card"><div className="card-heading"><div><h2>{location.name} rewards</h2><p>This offer appears in the selected location's customer page.</p></div></div><label className="full-field">Location reward offer<textarea value={offer} onChange={(event) => setOffer(event.target.value)} /></label><button className="admin-save settings-save" onClick={() => onSave({ rewardOffer: offer })}>Save reward offer</button></section>; }
function OrderManager({ orders, setOrders }) { return <section className="admin-card"><div className="card-heading"><div><h2>Order queue</h2><p>Manage direct orders across your locations.</p></div></div><OrderTable orders={orders} onChange={(id, status) => setOrders(orders.map((order) => order.id === id ? { ...order, status } : order))} /></section>; }
function OrderTable({ orders, onChange }) { return <div className="order-table"><div className="order-head"><span>Order</span><span>Guest</span><span>Location</span><span>Type</span><span>Total</span><span>Status</span></div>{orders.map((order) => <div className="order-row" key={order.id}><b>{order.id}</b><span>{order.guest}</span><span>{order.location}</span><span>{order.type}</span><span>{order.total}</span>{onChange ? <select value={order.status} onChange={(event) => onChange(order.id, event.target.value)}><option>New</option><option>Preparing</option><option>Ready</option><option>Completed</option></select> : <em>{order.status}</em>}</div>)}</div>; }
function Team() { return <section className="admin-card"><h2>Team access</h2><p>Owner access and location-manager roles will connect to secure authentication when the database is added.</p></section>; }
function AddLocation({ onClose, onSubmit }) { return <div className="modal-backdrop"><form className="location-modal admin-add" onSubmit={onSubmit}><button type="button" className="close-button" onClick={onClose}>×</button><p className="eyebrow">Restaurant group</p><h2>Add a new location</h2><label>Location name<input name="name" placeholder="Ambar India Oakley" autoFocus /></label><label>Street address<input name="address" placeholder="123 Main Street, Cincinnati, OH" /></label><label>Phone number<input name="phone" placeholder="(513) 000-0000" /></label><label>Customer menu message<textarea name="menuNote" placeholder="Fresh menu for this location." /></label><label>Reward offer<textarea name="rewardOffer" placeholder="Free Garlic Naan with orders over $35" /></label><button className="primary-button" type="submit">Create location →</button></form></div>; }
