import React, { useState } from 'react';
import ExperienceSections from './ExperienceSections.jsx';

const menu = [
  ['✦', 'Guest favourite', 'Chicken Tikka Masala', 'Lightly broiled chicken in a savoury tomato, onion, and cream sauce.', '$22.99'],
  ['●', 'Vegetarian favourite', 'Saag Paneer', 'House-made paneer cooked with spinach in a delicate tomato cream sauce.', '$22.99'],
  ['✧', 'Fresh from the tandoor', 'Garlic Naan', 'Soft Indian bread, warm from the clay oven and generously seasoned.', '$7.99'],
];
const locations = [
  ['Ambar India Clifton', '350 Ludlow Ave · Pickup · Delivery · Catering', '#menu'],
  ['Ambar India Downtown', 'Coming soon · Pickup · Delivery · Lunch', '#'],
  ['Ambar India Events', 'Coming soon · Catering · Private events', '#'],
];

function Brand() { return <a className="brand" href="#top">AMBAR <span>INDIA</span><small>RESTAURANT</small></a>; }
function ChefGuide() { return <a className="chef-guide" href="#menu" aria-label="Explore Ambar India menu"><img src="/assets/ambar-chef.png" alt="Ambar India chef reading the menu" /><span>Chef's picks<br /><b>Explore the menu</b></span></a>; }
function NearbyLocation() { const [label, setLabel] = useState('Ambar India Clifton'); const [detail, setDetail] = useState('350 Ludlow Ave · Pickup · Delivery · Catering'); const locate = () => { if (!navigator.geolocation) return; navigator.geolocation.getCurrentPosition(() => { setLabel('Your closest Ambar location: Clifton'); setDetail('Ready for pickup, delivery, dine-in and catering'); }, () => setDetail('Location access is optional — Clifton is selected by default.'), { timeout: 5000, maximumAge: 600000 }); }; return <section className="nearby-bar"><div><b>{label}</b><span>{detail}</span></div><button onClick={locate}>Use my location</button><a href="#menu">Order from Clifton →</a></section>; }

export default function App() {
  const [open, setOpen] = useState(false);
  return <><div className="announcement">Order directly from Ambar India · Save on fees · Earn rewards</div><NearbyLocation /><ChefGuide />
    <header className="site-header"><Brand /><nav><a href="#story">Our story</a><a href="#menu">Menu</a><a href="#catering">Catering</a><a href="#visit">Visit us</a></nav><button className="outline-button" onClick={() => setOpen(true)}>Order online <b>→</b></button></header>
    <main id="top">
      <section className="hero"><div className="hero-shade" /><div className="hero-copy"><p className="eyebrow">Cincinnati's home for Northern Indian cuisine</p><h1>A table full of<br /><em>India's warmth.</em></h1><p>From our tandoor to your table, Ambar India serves vibrant curries, fragrant basmati rice, handmade breads, and the generous hospitality of Northern India.</p><div className="hero-actions"><button className="primary-button" onClick={() => setOpen(true)}>Start your order <span>→</span></button><a className="light-link" href="#story">Discover Ambar <span>↓</span></a></div></div><div className="hero-badge"><span>Since</span><b>AMBAR</b><span>Authentic flavours · warmly served</span></div></section>
      <section className="quick-links"><a href="#menu"><span>01</span><b>Explore the menu</b><i>→</i></a><a href="#catering"><span>02</span><b>Catering & celebrations</b><i>→</i></a><a href="#visit"><span>03</span><b>Find your location</b><i>→</i></a></section>
      <section id="story" className="story section"><div className="story-art"><div className="arch"><span>31</span><p>Years of flavour,<br />family and heart</p></div></div><div className="story-copy"><p className="eyebrow">Our story</p><h2>Cincinnati's home for Northern Indian food for 31 years.</h2><p>Thirty-one years ago, Ambar India opened its doors with a dream, a handful of recipes, and a whole lot of heart. Since then, we have shared countless meals, stories, and memories with our Cincinnati community.</p><p>At 350 Ludlow Avenue, every tandoori dish, fragrant curry, and soft bread is prepared fresh daily. Whether it is a casual dinner, a family gathering, or a special celebration, every meal is made with care.</p><p className="story-thanks">Thank you for growing with us, laughing with us, and letting us be part of your lives. Here is to the past that built us and the future we are still cooking up.</p><div className="tags"><span>Since 1995</span><span>Fresh every day</span><span>Clifton, Cincinnati</span></div></div></section>
      <section id="menu" className="menu-section section"><div className="section-heading"><div><p className="eyebrow">Made for sharing</p><h2>Find your favourite flavour.</h2></div><button className="text-link" onClick={() => setOpen(true)}>Order the full menu <span>→</span></button></div><div className="menu-layout"><div className="menu-intro"><p>From crisp samosas and house-made naan to silky saag, aromatic biryani, and tandoor classics, our menu has something for every table.</p>{[['START WITH','Appetizers & soups','Samosas · pakoras · chaat · dal soup'],['FROM THE TANDOOR','Fire-kissed favourites','Chicken tikka · paneer tikka · tandoori chicken'],['CURRIES & MORE','Deeply comforting mains','Chicken · lamb · seafood · vegetarian specialities']].map(([label,title,text]) => <div className="menu-category" key={label}><span>{label}</span><b>{title}</b><small>{text}</small></div>)}</div><div className="featured-dishes">{menu.map(([mark,label,title,text,price], index) => <article key={title}><p className={`dish-mark ${index === 1 ? 'green-mark' : ''}`}>{mark}</p><span>{label}</span><h3>{title}</h3><p>{text}</p><strong>{price}</strong></article>)}</div></div></section>
      <section className="services"><p className="eyebrow">The Ambar experience</p><h2>However you gather,<br />we are ready to serve.</h2><div className="service-grid">{[['◉','Dine in','A relaxed, welcoming place to savour every course.'],['↗','Pickup & delivery','Your favourites, freshly prepared and ready when you are.'],['✦','Vegetarian options','Generous choice, rich flavour, and a true place at the table.'],['♜','Rewards','Earn points, enjoy free items, and hear about new offers first.']].map(([icon,title,text]) => <article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section id="catering" className="catering"><div className="catering-photo" /><div className="catering-copy"><p className="eyebrow">Catering for every occasion</p><h2>Bring the feast to your celebration.</h2><p>From weddings and birthdays to office lunches and special gatherings, our tandoori dishes, curries, and fresh breads make every occasion more memorable.</p><p>Planning a wedding or private event? Our team will help you build a menu your guests will love.</p><a className="primary-button" href="mailto:singhjag@fuse.net?subject=Ambar%20India%20catering%20enquiry">Plan your event <span>→</span></a></div></section>
      <section className="reviews section"><p className="eyebrow">Loved by our guests</p><h2>“The food has been top notch<br />and the service excellent.”</h2><div className="review-grid">{[['A delicious, fresh meal and wonderful care for dietary needs. We will definitely be returning.','Theresa H.'],['Tender, aromatic lamb, amazing garlic naan, friendly staff, and thoughtful portions.','Athiwat T.'],['A classy Indian restaurant—perfect for an evening out.','Joseph H.']].map(([quote,name]) => <article key={name}><span>★★★★★</span><p>“{quote}”</p><b>{name}</b></article>)}</div></section>
      <section id="visit" className="visit"><div><p className="eyebrow">Visit us today</p><h2>Your table in Clifton is waiting.</h2><p>Enjoy a relaxed meal in our restaurant, pick up your favourites, or order delivery. Fresh tandoori, curries, and naan are ready for you.</p><div className="visit-details"><p><b>Ambar India Restaurant</b><br />350 Ludlow Ave<br />Cincinnati, OH 45220</p><p><b>Call us</b><br />(513) 281-7000<br />singhjag@fuse.net</p></div><button className="primary-button" onClick={() => setOpen(true)}>Order from Clifton <span>→</span></button></div><div className="hours"><p className="eyebrow">Opening hours</p><p><b>Sunday</b><span>10:30 AM – 9:30 PM</span></p><p><b>Mon – Fri</b><span>10:30 AM – 10:00 PM</span></p><p><b>Saturday</b><span>10:30 AM – 10:00 PM</span></p><small>Hours shown should be verified per location before launch.</small></div></section>
      <section className="rewards"><div><p className="eyebrow">Ambar India rewards</p><h2>Good food deserves<br />good rewards.</h2><p>Join the rewards programme to earn points, receive free food, and stay up to date with Ambar India.</p><button className="light-button">Join rewards <span>→</span></button></div><div className="rewards-seal">AMBAR<br /><b>REWARDS</b><span>Eat · earn · repeat</span></div></section>
    <ExperienceSections /></main><footer><Brand /><div><a href="#menu">Menu</a><a href="#catering">Catering</a><a href="#visit">Contact</a></div><p>© 2026 Ambar India Restaurant</p></footer>
    {open && <div className="modal-backdrop" onMouseDown={() => setOpen(false)}><section className="location-modal" onMouseDown={(event) => event.stopPropagation()} role="dialog" aria-modal="true"><button className="close-button" onClick={() => setOpen(false)}>×</button><p className="eyebrow">Order Ambar India</p><h2>Choose your location</h2><p className="dialog-intro">We’ll show the right menu, opening hours, services, and offers.</p><div className="location-list">{locations.map(([name,detail,href]) => <a className="location-card" key={name} href={href}><span><b>{name}</b><small>{detail}</small></span><i>→</i></a>)}</div></section></div>}
  </>;
}
