import React, { useEffect, useMemo, useState } from 'react';

const fallback = [{ category: 'Appetizers', items: [['Vegetable Samosa', 9.89, 'Two crisp pastries with potatoes and green peas'], ['Paneer Pakora', 12.99, 'Lightly spiced and batter fried']] }];
const menuPhotos = { appetizers: '/assets/menu-samosa.png', soup: '/assets/menu-samosa.png', salad: '/assets/menu-samosa.png', tandoori: '/assets/menu-tandoori.png', chicken: '/assets/menu-tikka-masala.png', lamb: '/assets/menu-lamb-rogan-josh.png', shrimp: '/assets/menu-tandoori.png', fish: '/assets/menu-tandoori.png', vegetarian: '/assets/menu-saag-paneer.png', paneer: '/assets/menu-saag-paneer.png', rice: '/assets/menu-biryani.png', biryani: '/assets/menu-biryani.png', bread: '/assets/menu-garlic-naan.png', nan: '/assets/menu-garlic-naan.png', dessert: '/assets/menu-gulab-jamun.png', beverage: '/assets/menu-gulab-jamun.png' };
const photoFor = (category) => { const key = Object.keys(menuPhotos).find((item) => category.toLowerCase().includes(item)); return menuPhotos[key] || '/assets/menu-tikka-masala.png'; };
const priceNumber = (price) => Number(String(price).replace(/[^0-9.]/g, '')) || 0;
const priceLabel = (price) => typeof price === 'number' ? `$${price.toFixed(2)}` : `$${price}`;

export default function MenuCatalogue({ onAdd }) { const [categories, setCategories] = useState(fallback); const [cat, setCat] = useState('Appetizers'); useEffect(() => { fetch('/data/ambar-menu.json').then((response) => response.ok ? response.json() : Promise.reject()).then((data) => { if (data.categories?.length) { setCategories(data.categories); setCat(data.categories[0].category); } }).catch(() => {}); }, []); const active = useMemo(() => categories.find((item) => item.category === cat) || categories[0], [categories, cat]); const photo = photoFor(active.category); return <section id="full-menu" className="catalogue"><div className="catalogue-hero" style={{ backgroundImage: `linear-gradient(90deg,#270b11bd,#270b1120),url('${photo}')` }}><div><p className="eyebrow">Ambar India menu</p><h2>Made fresh.<br />Made to share.</h2><span>{active.hours || "Chef's picks, made for your table"}</span></div></div><div className="catalogue-tabs">{categories.map((item) => <button className={cat === item.category ? 'active' : ''} onClick={() => setCat(item.category)} key={item.category}>{item.category.replace(/^Lunch /, '')}</button>)}</div><div className="menu-category-note">{active.note && <span>{active.note}</span>}<b>{active.items.length} items</b></div><div className="catalogue-grid">{active.items.map((item) => { const name = item.name || item[0]; const price = item.price ?? item[1]; const description = item.description || item[2]; return <article className="menu-card" key={name}><div className="menu-card-photo" style={{ backgroundImage: `url('${photo}')` }} /><b>{name}</b><span>{priceLabel(price)}</span>{description && <p>{description}</p>}<button onClick={() => onAdd?.({ name, price: priceNumber(price) })}>Add to order +</button></article>; })}</div><small>Availability is confirmed when an order is placed.</small></section>; }
