import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from './supabaseClient.js';

const plans = { starter: 'Website · menu · reservations', growth: 'Ordering · POS · kitchen · team', pro: 'Multi-location · rewards · analytics' };
export default function PlatformDashboard() {
  const [session, setSession] = useState(null); const [ready, setReady] = useState(false); const [allowed, setAllowed] = useState(false); const [merchants, setMerchants] = useState([]); const [message, setMessage] = useState('');
  useEffect(() => { if (!supabase) return setReady(true); supabase.auth.getSession().then(({ data }) => { setSession(data.session); setReady(true); }); }, []);
  useEffect(() => { if (!session || !supabase) return; supabase.from('platform_admins').select('user_id').eq('user_id', session.user.id).maybeSingle().then(({ data }) => { setAllowed(Boolean(data)); }); }, [session]);
  const load = async () => { if (!supabase) return; const { data, error } = await supabase.from('organizations').select('id,name,slug,plan,status,tagline,created_at').order('created_at', { ascending: false }); if (error) return setMessage('Merchant accounts are unavailable until platform setup is complete.'); const { data: locations } = await supabase.from('locations').select('id,name,organization_id').eq('is_active', true); setMerchants((data || []).map((org) => ({ ...org, locations: (locations || []).filter((location) => location.organization_id === org.id) }))); };
  useEffect(() => { if (allowed) load(); }, [allowed]);
  const updateMerchant = async (id, patch) => { const { error } = await supabase.from('organizations').update(patch).eq('id', id); if (error) return setMessage('That merchant could not be updated.'); setMerchants((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item)); setMessage('Merchant account updated.'); };
  const totals = useMemo(() => ({ active: merchants.filter((item) => item.status === 'active').length, trial: merchants.filter((item) => item.status === 'trial').length, locations: merchants.reduce((sum, item) => sum + item.locations.length, 0) }), [merchants]);
  if (!ready) return <main className="platform-auth"><p>Loading platform access…</p></main>;
  if (!session) return <PlatformLogin />;
  if (!allowed) return <main className="platform-auth"><section><p className="eyebrow">Platform access</p><h1>This account is not a platform administrator.</h1><p>Sign in with your product-owner account to manage restaurant customers.</p><button className="platform-button" onClick={() => supabase.auth.signOut()}>Sign out</button></section></main>;
  return <div className="platform-shell"><aside className="platform-sidebar"><a className="platform-brand" href="/">AMBAR <span>DIRECT</span><small>PLATFORM ADMIN</small></a><p className="platform-kicker">PRODUCT CONTROL</p><nav><a className="active" href="/platform">Merchant accounts</a><a href="/admin">Open merchant portal</a></nav><div className="platform-sidebar-bottom"><span>{session.user.email}</span><button onClick={() => supabase.auth.signOut()}>Sign out</button></div></aside><main className="platform-main"><header className="platform-header"><div><p className="eyebrow">Platform admin</p><h1>Merchant control centre</h1><p>Onboard, support, and grow every restaurant using Ambar Direct.</p></div><button className="platform-button" onClick={load}>Refresh data</button></header><section className="platform-stats"><article><span>Total merchants</span><b>{merchants.length}</b><small>Restaurant workspaces</small></article><article><span>Active accounts</span><b>{totals.active}</b><small>Currently operating</small></article><article><span>Trial accounts</span><b>{totals.trial}</b><small>Need onboarding attention</small></article><article><span>Live locations</span><b>{totals.locations}</b><small>Across all merchants</small></article></section>{message && <p className="platform-message">{message}</p>}<section className="merchant-table"><div className="merchant-head"><span>Merchant</span><span>Plan</span><span>Status</span><span>Locations</span><span>Created</span></div>{merchants.map((merchant) => <article key={merchant.id}><span><b>{merchant.name}</b><small>{merchant.slug} · {merchant.tagline || 'No tagline set'}</small></span><select value={merchant.plan} onChange={(event) => updateMerchant(merchant.id, { plan: event.target.value })}>{Object.keys(plans).map((plan) => <option value={plan} key={plan}>{plan}</option>)}</select><select value={merchant.status} onChange={(event) => updateMerchant(merchant.id, { status: event.target.value })}><option value="active">Active</option><option value="trial">Trial</option><option value="past_due">Past due</option><option value="suspended">Suspended</option></select><span className="platform-locations">{merchant.locations.length}{merchant.locations.length ? <small>{merchant.locations.map((location) => location.name).join(' · ')}</small> : null}</span><time>{new Date(merchant.created_at).toLocaleDateString()}</time></article>)}</section></main></div>;
}
function PlatformLogin() { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const submit = async (event) => { event.preventDefault(); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) setMessage('Check your email and password.'); }; return <main className="platform-auth"><form onSubmit={submit}><p className="eyebrow">Ambar Direct</p><h1>Platform admin</h1><p>Manage every restaurant customer from one secure workspace.</p><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{message && <small>{message}</small>}<button className="platform-button" type="submit">Sign in →</button></form></main>; }
