import React, { useEffect, useState } from 'react';
import { supabase } from './supabaseClient.js';
import { PlatformNav } from './PlatformOperations.jsx';

export default function PlatformSupport({ session }) {
  const [domains, setDomains] = useState([]); const [tickets, setTickets] = useState([]); const [organizations, setOrganizations] = useState([]); const [message, setMessage] = useState(''); const [domain, setDomain] = useState({ organization_id: '', domain: '' });
  const load = async () => { const [{ data: orgs }, { data: domainRows }, { data: ticketRows }] = await Promise.all([supabase.from('organizations').select('id,name').order('name'), supabase.from('merchant_domains').select('*,organizations(name)').order('created_at', { ascending: false }), supabase.from('support_tickets').select('*,organizations(name)').order('created_at', { ascending: false })]); setOrganizations(orgs || []); setDomains(domainRows || []); setTickets(ticketRows || []); };
  useEffect(() => { load(); }, []);
  const addDomain = async (event) => { event.preventDefault(); const { error } = await supabase.from('merchant_domains').insert(domain); if (error) return setMessage('Could not add that domain.'); setDomain({ organization_id: '', domain: '' }); setMessage('Domain added.'); load(); };
  const updateTicket = async (id, status) => { await supabase.from('support_tickets').update({ status }).eq('id', id); setTickets((items) => items.map((item) => item.id === id ? { ...item, status } : item)); };
  return <div className="platform-shell"><PlatformNav session={session} /><main className="platform-main"><header className="platform-header"><div><p className="eyebrow">Platform operations</p><h1>Support & domains</h1><p>Keep merchant websites connected and every request moving.</p></div><button className="platform-button" onClick={load}>Refresh</button></header><section className="platform-support-grid"><section className="support-card"><p className="eyebrow">Custom website domain</p><h2>Connect a merchant domain</h2><form onSubmit={addDomain}><label>Merchant<select required value={domain.organization_id} onChange={(event) => setDomain({ ...domain, organization_id: event.target.value })}><option value="">Choose merchant</option>{organizations.map((org) => <option value={org.id} key={org.id}>{org.name}</option>)}</select></label><label>Domain<input required value={domain.domain} onChange={(event) => setDomain({ ...domain, domain: event.target.value })} placeholder="www.restaurant.com" /></label><button className="platform-button" type="submit">Add domain →</button></form>{message && <p className="platform-message">{message}</p>}<div className="domain-list">{domains.map((item) => <div key={item.id}><span><b>{item.domain}</b><small>{item.organizations?.name}</small></span><em className={item.status}>{item.status}</em>{item.status === 'pending' && <code>{item.verification_token}</code>}</div>)}</div></section><section className="support-card"><p className="eyebrow">Merchant support queue</p><h2>Open requests</h2><div className="ticket-list">{tickets.length ? tickets.map((ticket) => <article key={ticket.id}><div><b>{ticket.subject}</b><small>{ticket.organizations?.name} · {ticket.priority}</small></div><p>{ticket.description}</p><select value={ticket.status} onChange={(event) => updateTicket(ticket.id, event.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting">Waiting</option><option value="resolved">Resolved</option></select></article>) : <p className="support-empty">No support requests yet.</p>}</div></section></section></main></div>;
}
